helper/replacements: Fix Windows build using clang (-Wsign-compare)
OpenOCD currently won't build on Windows using clang for these
reasons:
- "-Wextra", which is enabled for OpenOCD builds by default,
  causes on clang that "-Wsign-compare" gets also enabled.
- Socket descriptors on Windows are unsigned, causing
  -Wsign-compare warnings on each invocation of FD_SET.

Possible workaround: ./configure [...] --disable-werror

Fix the issue by creating OCD_FD_* wrapper macros over FD_*
that add the missing cast on Windows, silencing those compiler
warnings.

Also make sure that -Wsign-compare gets enabled on GCC.

Steps to reproduce the issue:

1) Use a Windows machine
2) Download and install MSYS2 from: https://www.msys2.org
3) In the MSYS2 shell, install the following packages:

   pacman -S autotools automake base-devel mingw-w64-x86_64-clang git tcl

4) Clone libjaylink source

   git clone https://github.com/openocd-org/openocd.git --recursive
   cd openocd

5) Configure and build openocd

   export CC=/mingw64/bin/clang
   ./bootstrap
   ./configure \
       --enable-jtag_vpi \
       --enable-remote-bitbang \
       --prefix=`pwd`/install \
       --enable-internal-jimtcl
   make -j$(nproc)

6) Observe the sign-compare error message(s) produced by clang,
   for example:

src/helper/replacements.c:178:6: error: comparison of integers
of different signs: 'SOCKET' (aka 'unsigned long long') and
'int' [-Werror,-Wsign-compare]
  178 |  FD_SET(i, &sock_read);
      |  ^~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/psdk_inc/_fd_types.h:77:40:
note: expanded from macro 'FD_SET'
   77 | if (((fd_set *)(set))->fd_array[__i] == (fd)) {         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~

$ clang --version
clang version 21.1.7
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin

Change-Id: I164da7165c77f232ae83f6d60305360a87c7604a
Signed-off-by: Jan Matyas <jan.matyas@codasip.com>
Reviewed-on: https://review.openocd.org/c/openocd/+/9506
Reviewed-by: Antonio Borneo <borneo.antonio@gmail.com>
Tested-by: jenkins
Reviewed-by: Chris Head <chead@zaber.com>