flash/nor/tcl: Remove unused variable
Remove the unused variable. This additionally fixes the following build
issue:

../src/flash/nor/tcl.c: In function 'handle_flash_banks_command':
../src/flash/nor/tcl.c:1445:22: error: variable 'n' set but not used [-Werror=unused-but-set-variable=]
 1445 |         unsigned int n = 0;
      |

Tested with GCC 16.1.1

Change-Id: Id033101f9caf51f87622e872234b8520bf31d9f0
Signed-off-by: Marc Schink <dev@zapb.de>
Reviewed-on: https://review.openocd.org/c/openocd/+/9728
Tested-by: jenkins
Reviewed-by: Antonio Borneo <borneo.antonio@gmail.com>